version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3001:3001"

  db:
    container_name: sports_db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: